jobs:
  support:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dessant/support-requests@v2
      with:
        close-issue: true
        github-token: ${{ github.token }}
        issue-comment: ':wave: @{issue-author}, sorry you''re having an issue. As
          the issue template explains, we require that you provide a runnable example
          that reproduces your issue (please read the [issue template](https://raw.githubusercontent.com/react-native-google-signin/google-signin/master/.github/ISSUE_TEMPLATE/Custom.md)).

          The reason is that maintainers do not have time to try reproduce bugs themselves.
          Please try to minimize the superfluous code and focus only on reproducing
          the bug.

          Please create a new issue with this and we''ll be happy to review it! If
          you''re hitting a hard wall, you may consider [paid assistance](https://github.com/react-native-google-signin/google-signin/pull/861).

          '
        lock-issue: false
        support-label: repro-required
name: Support requests
on:
  repository_dispatch:
    types: trigger-ga___support.yml
