jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - continue-on-error: true
      run: yarn install --frozen-lockfile
    - continue-on-error: true
      run: yarn test
    - continue-on-error: true
      run: yarn typescript
    - continue-on-error: true
      run: yarn prettier:check
    - continue-on-error: true
      run: yarn lint
  publish-npm:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - continue-on-error: true
      run: yarn install --frozen-lockfile
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn release
name: test and publish
on:
  repository_dispatch:
    types: trigger-ga___test_lint_publish.yml
